#=========================== Filebeat inputs =============================
filebeat.inputs:
  - type: log
    paths:
      - /logs/*.log

#----------------------------- Logstash output --------------------------------
output.elasticsearch:
  hosts: ${ELASTIC_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
