name: Docker Image CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Check out code

      - name: Set env from github secrets
        run: |
          SECRETS=$(env | grep -oP '^(?!DOCKER_)\K.*')
          for secret_name in $SECRETS; do
            echo "Setting $secret_name=${{ secrets[$secret_name] }}"
            echo "::set-env name=$secret_name::${{ secrets[$secret_name] }}"
          done

      - name: Generate config.yml
        run: |
          envsubst < config.template.yml > config.yml

      - name: Show generated config.yml
        run: cat config.yml

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: duongsonn/local-app-oauth-server
          tags: v1, latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
